name: KELL-CUMMING
favicon: null
layout_spectrum: 0.53477
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4422b'
    - '#404042'
    - '#ff0000'
    - '#000000'
    - '#aa5500'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
